// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hnyzydrazexsopfobyzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhueXp5ZHJhemV4c29wZm9ieXpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY2OTkxNTksImV4cCI6MjA1MjI3NTE1OX0.9wW6RW7iEq4wb9DruOqQNvH3qUjMWi_uULawo0uHvSA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);